name: biggan-clip
channels:
  - default
  - pytorch
dependencies:
  - python=3.8
  - pip
  - pytorch=1.7.1
  - torchvision=0.8.2
  - cudatoolkit=10.2
  - pip:
    - scipy
    - pycocotools
    - ftfy
    - regex
    - tqdm
    - git+https://github.com/openai/CLIP.git
